### PR TITLE
fix: phpstan error

### PR DESCRIPTION
**Pull request by datamweb**
https://github.com/codeigniter4/shield/actions/runs/3358795822/jobs/5566185102
```consel
P:\MyGitHubWork\shield>php vendor/bin/phpstan analyze
Note: Using configuration file P:\MyGitHubWork\shield\phpstan.neon.dist.
 119/119 [============================] 100%

 ------ ----------------------------------------------------------------------------------------------------
  Line   src\Controllers\MagicLinkController.php
 ------ ----------------------------------------------------------------------------------------------------
  168    Parameter #2 $value of method CodeIgniter\Session\Session::setTempdata() expects null, true given.
 ------ ----------------------------------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by paulbalandan** [comment]
The code works. It is just the PHPDocs in `setTempData` is wrong.

**Comment by datamweb** [comment]
@MGatner Please check here before releasing a new version of CI.

https://github.com/codeigniter4/CodeIgniter4/blob/1423c7177bbe2fdab725aa3d7284093e97e93c72/system/Session/Session.php#L748

**Comment by kenjis** [comment]
I sent a PR: https://github.com/codeigniter4/CodeIgniter4/pull/6796

**Comment by MGatner** [comment]
Thanks all

**Comment by datamweb** [comment]
I'm closing this PR, because it's resolved in #6796.

**Pull request closed without merging**
