### PR TITLE
refactor: remove unneeded Entities\Cast\IntBoolCast

### PR DESCRIPTION
**Pull request by grimpirate**
**Description**
While looking at the shield source code it was noted that the [IntBoolCast class is already provided by codeigniter](https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/Entity/Cast/IntBoolCast.php). Furthermore, the int_bool cast handler of the custom shield Entity [already provided as an int-bool in the framework's default Entity](https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/Entity/Entity.php#L98). This commit cleans up redundant code.

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by datamweb — COMMENTED** [review]
I’m not entirely sure, but as far as I remember, these features were added to the framework after they were identified as necessary in Shield. Since Shield also supports older versions of the framework, we need to ensure that these changes do not break compatibility.

Could you please investigate which version of the framework these features were introduced in and make sure that the proposed changes will not cause issues with older versions?

**Comment by kenjis** [comment]
Thank you for sending this PR.
Also, please fix all errors in GitHub Actions.

**Comment by grimpirate** [comment]
You were correct regarding supporting older framework it appears datamweb: see [here](https://github.com/codeigniter4/CodeIgniter4/commit/076a5427b69060080f86d45e15b0f91ab152138e) and [here](https://github.com/codeigniter4/CodeIgniter4/commit/899187a79363596342c5710c761f980a35d373b6). Feature was implemented approximately two years ago.

**Comment by kenjis** [comment]
@datamweb 

We have phpunit test "[phpunit / PHP 7.4 - MySQLi - lowest](https://github.com/codeigniter4/shield/actions/runs/10569805908/job/29283249126?pr=1186#logs)" that installs the lowest dependencies.
But it installs v4.4.7.

- Installing codeigniter4/framework (v4.4.7): Extracting archive

Ah, that is because v4.4.6 or below has one or more known vulnerabilities.
https://github.com/codeigniter4/CodeIgniter4/security/advisories

**Comment by kenjis** [comment]
@grimpirate See the version tags.
Screenshot 2024-08-27 10 30 15
https://github.com/codeigniter4/CodeIgniter4/commit/899187a79363596342c5710c761f980a35d373b6

**Comment by kenjis** [comment]
@grimpirate Why did you close this?
IntBoolCast has been introduced in v4.3.0, and Shield requires v4.3.5 or later.
See https://shield.codeigniter.com/getting_started/install/#requirements

**Comment by grimpirate** [comment]
@kenjis sorry about that I thought based on the commit history that it was for backwards compatibility. I didn't think to compare the version numbers.

**Comment by kenjis** [comment]
@grimpirate Okay, no problem. As you see, your refactoring is okay.
So if you send the PR again, we would review and merge.

**Pull request closed without merging**
