### PR TITLE
fix: only validate data from POST request body

### PR DESCRIPTION
**Pull request by miguel-rn**
With the current data validation checks in the controllers, an empty POST request with valid GET parameters will cause the validation to pass. Since this data is always later fetched from the POST request body, it will be null and errors will be thrown.

### CODE REVIEW

**Review by kenjis — APPROVED** [review]
Thank you. You're correct. Using `$this->validate()` is not a good practice.

**Review by datamweb — APPROVED** [review]

**Comment by miguel-rn** [comment]
I noticed a related issue in the docs, I will make a pull request to update.

**Comment by sammyskills** [comment]
This is good, but I have to ask.

_Is it possible for a `$_GET` request to pass through a route defined as `$_POST`, i.e., `$route->post()` ?_

**Comment by sammyskills** [comment]
Maybe I didn't explain properly, I was actually talking about the `GET` request, in respect to the route definitions:
```php
$routes->get();
$routes->post();
```
For a route defined explicitly as `$route->post()`, can `$this->request->getGet()` pass through it?

**Comment by sammyskills** [comment]
My main concern is, for example, there is a route definition for the `loginAction()` method like so:
```php
$routes->post('login', 'LoginController::loginAction');
```
Is it possible that `GET` parameters will pass the validation using `$this->validate()` method?

**Comment by kenjis** [comment]
> For a route defined explicitly as `$route->post()`, can `$this->request->getGet()` pass through it?

Yes. Because `$this->request->getGet()` returns `$_GET` values.

> Is it possible that `GET` parameters will pass the validation using `$this->validate()` method?

Yes. Because `$this->validate()` maybe validates `$request->getVar()` data.
See the Warning: https://codeigniter4.github.io/CodeIgniter4/incoming/controllers.html#this-validate

**Pull request merged**
