### PR TITLE
Added spark command to manage users

### PR DESCRIPTION
**Pull request by robertogerola**
Supersedes #567

./spark shield:user 

Valid arguments : 'create', 'activate', 'deactivate', 'changename', 'changeemail', 'delete', 'password', 'list', 'addgroup', 'removegroup'

Valid options :
'-i'  => 'User id'
'-u'  => 'User name'
'-e'  => 'User email'
'-nu' => 'New username'
'-ne' => 'New email'
'-g'  => 'Group name'

### CODE REVIEW

**Comment by robertogerola** [comment]
Hi @datamweb, I signed my commit. Thanks for the heads-up.

**Comment by datamweb** [comment]
Hello @robertogerola .
I saw that you worked hard.
Thank you for trying.

1. **It is better to create a new branch in each PR post.**


How to do this?
```console
git branch feat-add-users-manage-whit-cli
```
2. **Every commit that is done must be signed.**


How to do this? 
https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account

3. **We need unit testing for code control and extensibility for each PR.**
How do you do it?
https://github.com/codeigniter4/CodeIgniter4/tree/develop/tests#resources

4. I saw your code superficially, your code needs a lot of changes, however I did not review it, I would like you to fix some problems yourself and then I or my colleagues will review it, for example:


- What is the output of command `php spark shield:user`? Without performance, it's not interesting.

```console
P:\Bug\project-root>php spark shield:user

CodeIgniter v4.2.10 Command Line Tool - Server Time: 2022-12-24 08:47:09 UTC-06:00
```

- The output of command `list` is not interesting, it can be as follows:
```console
P:\Bug\project-root>php spark shield:user list

CodeIgniter v4.2.10 Command Line Tool - Server Time: 2022-12-24 08:54:42 UTC-06:00

Id      User
21      datamweb (pooya@yahoo.com)
27      Kenji  (kenji@ci.dv)
```

```console
+----+--------------------------+---------------------+--------+
| ID | Title                    | Updated At          | Active |
+----+--------------------------+---------------------+--------+
| 7  | A great item title       | 2017-11-16 10:35:02 | 1      |
| 8  | Another great item title | 2017-11-16 13:46:54 | 0      |
```
How do you do it? 
https://codeigniter4.github.io/CodeIgniter4/cli/cli_library.html#table

At each stage you may face questions and challenges. Don't worry, try again if you couldn't send a message.

**Comment by robertogerola** [comment]
Thanks, I think it is better if I create a new branch and close this PR indeed. I'd like to work in the near future  on a web backend with the same features (CRUD interface on users) and having everything under the same main branch (develop) will create a lot of confusion and wouldn't be cleanly manageable. 
I'll work also on the other suggestions :

1. output on calling the command without argument : instructions for the user how to use the command
2. formatting the list output : I avoided to add a table style format to keep code simple, but it would be a nice-looking feature

**Comment by datamweb** [comment]
> I'd like to work in the near future on a web backend with the same features (CRUD interface on users)

If you mean sending PR to create **Admin** panel. You should know that Shield is an Authentication and Authorization , not a **Admin panel** standby system.

So we want to keep it that way.
If you want to use ready-made panels, [Bonfire2](https://github.com/lonnieezell/Bonfire2) is implemented with Shield, so you can use it.

But if you want to help Codeigniter community, you can share it with the community through [discussions](https://github.com/codeigniter4/shield/discussions) after finishing the work.

This is my personal opinion, other members may have a different opinion.

**Pull request closed without merging**
