### PR TITLE
Add the capacity to check multiple permissions.

### PR DESCRIPTION
**Pull request by solomon-ochepa**
* can() method now accepts both string and array arguments.
* Create Group model, entity, and migration.
* Create Permission model, entity, and migration.
* Rename and update the model Group -> GroupUser.
* Rename and update the model Permission -> PermissionUser.
* Merge file-based permissions with database query results.

### CODE REVIEW

**Comment by kenjis** [comment]
Thank you for sending PR.

But your PR and a commit is too big. Atomic commit is recommended.
Please read https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#committing

**Comment by kenjis** [comment]
First of all, you must GPG-sign your commits.
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#signing

**Comment by solomon-ochepa** [comment]
> Thank you for sending PR.
> 
> But your PR and a commit is too big. Atomic commit is recommended. Please read https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#committing

That is true. I'll look into that in my subsequent PR.

Thank you.

**Comment by kenjis** [comment]
I recommend you send a very small PR that contains only:
- can() method now accepts both string and array arguments.

Creating a fine PR that would be merged is not an easy task especially to new contributors.
There are a lot of tasks.

We also invite you to skim https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md.
If you have any questions, please feel free to ask.

**Pull request closed without merging**
