### PR TITLE
better website for docs

### PR DESCRIPTION
**Pull request by datamweb**
**Description**

https://datamweb.github.io/shield/

Screenshot 2023-09-25 123843

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Review by kenjis — APPROVED** [review]
LGTM! 👍

**Comment by kenjis** [comment]
Ah, there some code that I can't see well in the dark mode.
Screenshot 2023-09-25 18 12 50

**Comment by datamweb** [comment]
Thank you, I will try to fix it in the new PR.

**Comment by kenjis** [comment]
To be honest, the purple strings seem to be a bit too dark, too.
But this is better than above.
Screenshot 2023-09-25 18 20 12

**Comment by datamweb** [comment]
Screenshot 2023-09-25 152553

@kenjis if you can please check.
Let me know if it needs to be changed.

https://datamweb.github.io/shield/customization/redirect_urls/?h=loginredirect#customize-login-redirect

**Comment by kenjis** [comment]
@datamweb Thank you! It is very easy to read!

**Pull request merged**
