### PR TITLE
fix: cannot override `emailer()` function

### LINKED ISSUE #1173: Bug: `defined()` used for function
### PHP Version

8.3

### CodeIgniter4 Version

4.5.4

### Shield Version

dev-develop 223fbd9

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySQL 8.0.39

### Did you customize Shield?

No

### What happened?

In an attempt to create an `email_helper` and override the `emailer` function the system produces an error trying to redefine that function because the verification of a previously defined function of identical name is done using `defined` instead of `function_exists`.

### Steps to Reproduce

Copy codeigniter4/shield/src/email_helper.php into app/Helpers

### Expected Output

No error when overriding the `emailer` function

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by fch4um0n7**
**Description**
Fixes #1173

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by datamweb** [comment]
Please sign all your commits.

See:
https://github.com/codeigniter4/shield/pull/672#issuecomment-1468658726

More Info:
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#signing

**Comment by fch4um0n7** [comment]
> Please sign all your commits.
> 
> See: [#672 (comment)](https://github.com/codeigniter4/shield/pull/672#issuecomment-1468658726)
> 
> More Info: https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#signing

Sorry about that. It should be signed now

**Comment by datamweb** [comment]
> It should be signed now

No, see:
https://github.com/codeigniter4/shield/pull/672#issuecomment-1468722608

**Comment by fch4um0n7** [comment]
> > It should be signed now
> 
> No, see: [#672 (comment)](https://github.com/codeigniter4/shield/pull/672#issuecomment-1468722608)

Sorry, first time signing commits. Hopefully it is signed now

**Review by datamweb — APPROVED** [review]
> Sorry, first time signing commits. Hopefully it is signed now

No problem at all! Signing commits for the first time can be a bit tricky. Your commit are now signed, you’re all set!
And thanks again for your contribution—it's much appreciated!

LGTM!

**Comment by fch4um0n7** [comment]
> > Sorry, first time signing commits. Hopefully it is signed now
> 
> No problem at all! Signing commits for the first time can be a bit tricky. Your commit are now signed, you’re all set! And thanks again for your contribution—it's much appreciated!
> 
> LGTM!

Awesome! Keep up the good work. Thank you

**Comment by datamweb** [comment]
@FrancoisChaumont Please do not close PR. Wait for your code to be reviewed and **merged** by other team members.

**Comment by fch4um0n7** [comment]
> @FrancoisChaumont Please do not close PR. Wait for your code to be reviewed and **merged** by other team members.

Apologies. Ok

**Review by kenjis — APPROVED** [review]

**Comment by kenjis** [comment]
@FrancoisChaumont Thank you!

**Pull request merged**
