### PR TITLE
fix: show validate errors in `magic-link`

### PR DESCRIPTION
**Pull request by datamweb**
Fixes: https://github.com/codeigniter4/shield/pull/350#issuecomment-1207656514

### CODE REVIEW

**Comment by datamweb** [comment]
Hi @kenjis, I had to edit file `tests/Authentication/MagicLinkTest.php`.
We have two test files for `MagicLink` :
 `tests/Authentication/MagicLinkTest.php` and `tests/Controllers/MagicLinkTest.php`.

**Please check more carefully.**

**Comment by kenjis** [comment]
Why do you think this is bug fix?
Why do you need to show the validation error?

**Comment by datamweb** [comment]
Currently, the shield is displaying message `Unable to verify the email address matches the email on record`.  if the email is empty!
Or if it is email format wrong, the email form will display message `Unable to verify the email address matches the email on record`!
Maybe there is no problem in the performance of the Shield, **but is actually not displaying the correct message**.
Block `if ` is related to validation, so it is reasonable to display the messages related to validation and not `Auth.invalidEmail`.

Can you explain to me why message `Auth.invalidEmail` should be displayed instead of message `The Email Address field is required.` when the form is empty?

**Review by MGatner — APPROVED** [review]
Very nice! Thank you @datamweb

**Comment by MGatner** [comment]
@datamweb I tried emailing you on 7/31 (@yahoo.com) but heard no response. Is there a better way to get in touch with you? Are you on the CodeIgniter Slack?

**Comment by datamweb** [comment]
> datamweb I tried emailing you on 7/31 (@yahoo.com) but heard no response. Is there a better way to get in touch with you? Are you on the CodeIgniter Slack?

@MGatner Yes , I received your email.
I replied to your email on **1 August**.
It seems that you had a problem receiving my email.
I sent you the email again today.

Also, I have registered in slack after receiving your email.
**datamweb.slack.com** and my email (@yahoo.com).

In any case, if you do not succeed in contacting me, please let me know.

**Comment by kenjis** [comment]
I'm not sure what error message is better.

> why the message Auth.invalidEmail should be displayed when the length of the entered email is more than 254 characters?

It is kind of an attack. We don't need to response kindly.
There is also Security vs Usability issue.

**Comment by datamweb** [comment]
> It is kind of an attack. We don't need to response kindly. There is also Security vs Usability issue.

I believe the code should be secure enough that I don't need to hide it.
On the other hand, I believe that the failure to display the messages correctly will destroy user-friendliness.
However, your experience in this matter is higher, and if you think that these PR will harm the security of the shield, I respect it.
Please let me know so I can close.

**Comment by kenjis** [comment]
The security concern about the magic-link page is that attackers know that the email address exists in the database.
Ref #264

In the current implementation, attackers easily know it from the error message.
Screenshot 2022-08-13 17 10 07
Screenshot 2022-08-13 17 10 23

On the other hand, this PR just gives validation error messages.
An invalid email address is never be the address in the database.
So attackers do not send such a email address.

The conclusion is this PR does not increase the security risk.

**Review by kenjis — APPROVED** [review]

**Comment by datamweb** [comment]
> In the current implementation, attackers easily know it from the error message.

@kenjis, encouraging users to use captcha on magic-link, can it be useful?
If yes, we can create a note in the documents.

**Comment by kenjis** [comment]
@datamweb To increase the cost of posting the form is a mitigation.
Overall risk can be lowered. Captcha or rate limit can be used.

However, it may not be very useful if an attacker wants to find out if one particular person's e-mail address is registered.

**Comment by datamweb** [comment]
So we have this issue in case  `$registrationEmailRules` as well.

**Pull request merged**
