### PR TITLE
translate lang [id]

### PR DESCRIPTION
**Pull request by kikuKeii**
**Description**
I have changed `src\Language\id\Auth.php`. Because there are sentences that have not been translated

**Checklist:**
- [ ] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
Hi, the following test failed. Please fix.

```
1) Tests\Language\IndonesianTranslationTest::testAllIncludedLanguageKeysAreTranslated with data set "id" ('id')
Failed asserting that the translated language key "Auth.token" in "id" locale differs from the original keys in the main repository.
Failed asserting that an array is empty.

/home/runner/work/shield/shield/tests/Language/AbstractTranslationTestCase.php:260
```

**Comment by kenjis** [comment]
You must [GPG-sign](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/signing.md) your work, certifying that you either wrote the work or otherwise have the right to pass it on to an open-source project. See [Developer's Certificate of Origin](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/DCO.md).
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#signing

**Comment by kenjis** [comment]
The signing is Unverified.
Screenshot 2023-10-17 19 33 27
Screenshot 2023-10-17 19 33 37

**Comment by datamweb** [comment]
@kikuKeii  See https://github.com/codeigniter4/shield/pull/672#issuecomment-1468658726

**Comment by kikuKeii** [comment]
sorry, I will make a new pull request after I setup GPG-sign on my account

**Pull request closed without merging**
