### PR TITLE
Translate new strings to pt-BR

### PR DESCRIPTION
**Pull request by onovaes**
Added portuguese (PT-br) translations

### CODE REVIEW

**Comment by datamweb** [comment]
@onovaes Thank you for sending this PR.

You must sign the commit with GPG. This will cause the changes to be registered in your name.
The commitment to be signed will be as follows:

68747470733a2f2f646f63732e6769746875622e636f6d2f6173736574732f63622d3131313533382f696d616765732f68656c702f73657474696e67732f6770672d76657269666965642d776974682d657870697265642d6b65792e706e67

**See:**
https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account
And 
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#signing

**Comment by onovaes** [comment]
Hi @datamweb,  thanks for the reply. This is my first time.

I did right now?

**Comment by datamweb** [comment]
> This is my first time

Welcome.


> I did right now?

No, because **All** commits are not signed.

Screenshot 2023-03-14 231114

> Or should I open a new PR?

How to sign past commits is explained [here](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#gpg-signing-old-commits), **but feel free to do so if you're comfortable creating new PRs.**

**Comment by onovaes** [comment]
I Will open another PR

**Pull request closed without merging**
