### PR TITLE
Add test for checking localization parameters are not translated

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
See https://github.com/codeigniter4/shield/pull/954#issuecomment-1817960690

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by datamweb — APPROVED** [review]
This is what I wanted, it works fine on local.
```console
There was 1 failure:

1) Tests\Language\UkrainianTranslationTest::testAllLocalizationParametersAreNotTranslated with data set "uk" ('uk')
Failed asserting that parameters of translation keys are not translated:
  * Auth.errorPasswordLength => {0, number}
  * Auth.errorPasswordPwned => {1, number}
  * Auth.errorPasswordTooLongBytes => {param}
Failed asserting that an array is empty.

P:\MyGitHubWork\shield\tests\Language\AbstractTranslationTestCase.php:348
```
@paulbalandan , thank you for doing it.

**Comment by paulbalandan** [comment]
I just realized this may not work if a key has several parameters. I'll fix it tomorrow.

**Review by datamweb — APPROVED** [review]
Excellent. Thank you.

```console
18) Tests\Language\FarsiTranslationTest::testAllLocalizationParametersAreNotTranslated with data set "fa" ('fa')
Failed asserting that parameters of translation keys are not translated:
  * Auth.throttled => {1}
  * Auth.unknownAuthenticator => {1, number}, {2, number}, {3, number}
Failed asserting that an array is empty.
```

**Review by kenjis — APPROVED** [review]
LGTM!

**Pull request merged**
