### PR TITLE
chore: add issue templete

### PR DESCRIPTION
**Pull request by kenjis**
Copied from CodeIgniter4 repository, and tweaked.

### CODE REVIEW

**Comment by datamweb** [comment]
Considering that Shield allows customizable in different parts, it seems that you have made an option similar to which part of customizable? It can be useful.
See [comment](https://github.com/codeigniter4/shield/issues/314#issuecomment-1193868437) . 
In the PHP version section, it can be helpful to enter the exact version, for example, 7.4.3, see #319.

**Comment by kenjis** [comment]
Thanks for the good comment. I updated.

**Review by MGatner — CHANGES_REQUESTED** [review]
You have a few changes that appear to be from other branches. The templates look great though, thanks for setting this up!

**Comment by kenjis** [comment]
Removed irrelevant commits.

**Review by MGatner — APPROVED** [review]

**Pull request merged**
