### PR TITLE
lang: [ar] adding Arabic translation support to shield

### PR DESCRIPTION
**Pull request by mshannaq**
adding support of Arabic Language

### CODE REVIEW

**Comment by datamweb** [comment]
@mshannaq Thank you for PR.

Please sign the all commits:
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#gpg-signing-old-commits

More info https://github.com/codeigniter4/shield/pull/672#issuecomment-1468658726

Please add the test, see this comment:

https://github.com/codeigniter4/shield/pull/235#issuecomment-1153050805

**Comment by kenjis** [comment]
The first two commits are not signed.
Also, please do not include merge commits like 8cb712b.

**Comment by kenjis** [comment]
What did you do? It seems this PR branch is broken.
8cb712b and 26ecac1 are exactly the same.

**Comment by kenjis** [comment]
If you don't know how to use git, I recommend you try https://learngitbranching.js.org/

**Pull request closed without merging**
