### PR TITLE
Remove supportOldDangerousPassword support

### LINKED ISSUE #771: Dev: remove supportOldDangerousPassword before v1.0.0 release
See https://github.com/codeigniter4/shield/blob/develop/UPGRADING.md#if-you-want-to-allow-login-with-existing-passwords

https://github.com/codeigniter4/shield/blob/0bf28b24e6f2e7954e67cb686ce214d639812113/src/Config/Auth.php#L377-L385

### PR DESCRIPTION
**Pull request by omerimzali**
Fixes #771 

Ref: https://github.com/codeigniter4/shield/commit/ea9688dd01d100193d834117dbfc2cfabcf9ea0b

**Description**
I removed supportOldDangerousPassword. And also there is no usage of verifyDanger() anymore I also deleted it. I didn't update the docs because docs already have the information about deprecation for version 1.0.0 release.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by datamweb** [comment]
@omerimzali,
Please fix [phpStan ](https://github.com/codeigniter4/shield/actions/runs/6361436050/job/17276235533?pr=867)by changing below to **8**:

https://github.com/codeigniter4/shield/blob/1d9a659dae107ceff1f65700f2f789b8df4ad28e/phpstan-baseline.php#L321


Also, run the following command to [fix the code style](https://github.com/codeigniter4/shield/actions/runs/6361436057/job/17276235570?pr=867):

```console
composer cs-fix
```

**Comment by omerimzali** [comment]
@datamweb Allright I'll try these and update the PR.

**Comment by datamweb** [comment]
> Allright I'll try these and update the PR.

what do you mean?

Screenshot_2023-09-30-15-54-03-877-edit_com android chrome

**Comment by omerimzali** [comment]
@datamweb I repushed the PR with sign. It was not easy to sign last 3 commits I'm not sure if it went well. and with change of this line below like you mentioned. I use composer-fix but here's the thing, I don't really know why did you ask to change this phpstan config.


https://github.com/codeigniter4/shield/commit/1d9a659dae107ceff1f65700f2f789b8df4ad28e
` 'count' => 8,`

Feel free to reject the PR I can create a fresh one if it's not okay.

**Comment by datamweb** [comment]
> I use composer-fix but here's the thing, I don't really know why did you ask to change this phpstan config.

The reason for this request was the failure in examination phpstan. In fact, we had already suppressed the **number of 9 errors** detected by PHPStan.

With this PR you have removed the following code:
```php
    public function testCheckSuccessOldDangerousPassword(): void
    {
        /** @var Auth $config */
        $config                              = config('Auth');
        $config->supportOldDangerousPassword = true; // @phpstan-ignore-line

        fake(
            UserIdentityModel::class,
            [
                'user_id' => $this->user->id,
                'type'    => Session::ID_TYPE_EMAIL_PASSWORD,
                'secret'  => 'foo@example.com',
                'secret2' => '$2y$10$WswjNNcR24cJvsXvBc5TveVVVQ9/EYC0eq.Ad9e/2cVnmeSEYBOEm',
            ]
        );

        $result = $this->auth->check([
            'email'    => 'foo@example.com',
            'password' => 'passw0rd!',
        ]);

        $this->assertInstanceOf(Result::class, $result); // This causes an error
        $this->assertTrue($result->isOK());

        $foundUser = $result->extraInfo();
        $this->assertSame($this->user->id, $foundUser->id);
    }

```

Therefore, one error will be less.

Regarding command `composer cs-fix`, this command automatically checks the code styles and fixes it if there is a problem.

As you can see now, everything turned green:

Screenshot 2023-09-30 194532

**Comment by datamweb** [comment]
> I repushed the PR with sign. It was not easy to sign last 3 commits I'm not sure if it went well.

Please refer to the link below:

https://github.com/codeigniter4/shield/pull/672#issuecomment-1468658726
https://github.com/codeigniter4/shield/pull/672#issuecomment-1468722608

**Comment by omerimzali** [comment]
@datamweb Thank you for all these explanations. Specially on PHPStan part. I was confused at first about replacing 9 to 8.

No I think ı signed well. It seems legit.
image

**Comment by omerimzali** [comment]
@datamweb  🙏  PR need a reviewer and approving review by reviewers, but will you wait to merge because of the scope of this PR?

**Comment by datamweb** [comment]
@omerimzali I added a [ref link](https://github.com/codeigniter4/shield/commit/ea9688dd01d100193d834117dbfc2cfabcf9ea0b)  to your PR description, but haven't had time to review it carefully yet.
Changes may be needed, in any case you will be notified.

@kenjis, what's the next version?

**Comment by kenjis** [comment]
The next version is 1.0.0-beta.7.

**Comment by omerimzali** [comment]
@datamweb thank you, feel free to ping me for any changes.

**Comment by kenjis** [comment]
No feedback.
Closed by #976

**Pull request closed without merging**
