### PR TITLE
docs: mobile token guides

### PR DESCRIPTION
**Pull request by lonnieezell**
Adds a guide describing one way of using Access Tokens to authenticate a mobile application. 

Requires #417 to be merged first.

### CODE REVIEW

**Comment by MGatner** [comment]
Awaiting the other PR and rebase before review.

**Comment by kenjis** [comment]
Rebased.

**Comment by kenjis** [comment]
Added small fixes.

**Review by MGatner — APPROVED** [review]
This is rather opinionated but I like it as a practical example of a real and common scenario in webdev.

**Comment by datamweb** [comment]
Is this explanation comprehensive, what about tablets, smart watches and ...?
Wouldn't it be better to use **smart devices** instead of mobile?

**Comment by lonnieezell** [comment]
Thanks for the additional work here @kenjis.

@MGatner The code is mostly taken from the existing login method. 

I still want to look into how we do SPA authentication and provide a guide for that. I feel that might need a new method added, but unsure yet. If we use the session filter for SPAs I think we need to provide a way for an API to get a CSRF token. If we go with tokens for SPA's there needs to be some careful consideration there as that would leave the token exposed to anyone who wanted to look. So would probably have to put the token in a cookie or something to hide it? Unsure at the moment.

**Review by kenjis — APPROVED** [review]

**Pull request merged**
