### PR TITLE
fix: `shield:user create` with default group

### LINKED ISSUE #998: Bug: spark cli does not assign a default group to newly created user
### PHP Version

8.2.14

### CodeIgniter4 Version

4.4.4

### Shield Version

dev

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

apache

### Database

MariaDB 10.2

### Did you customize Shield?

No

### What happened?

While creating a new user from the cli, the `php spark shield:user create` command does not assign any group to the user (if not using the group option/parameter). 
I think the command should assign a default group to the newly created user by using the following setting: `config(\Config\AuthGroups::class)->defaultGroup` in order to avoid possible permissions issues at the first login attempt.

### Steps to Reproduce

```bash
php spark shield:user create

Username : bgeneto
Email : bgeneto@mail.com
Password : *******
Password confirmation : *******
User "bgeneto" created
```

### Expected Output

A corresponding line in the `auth_groups_users` table using the default group from `config(\Config\AuthGroups::class)->defaultGroup`.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by datamweb**
**Description**
fix: #998 

The user registration form sets the default group value for the user when a new user is registered. Although I don't consider this a bug, I prefer that this process be done for command `shield:user create` as well.

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by datamweb** [comment]
Two items.
I don't know why Rector has not been updated to the latest version by **Dependabot**. Maybe it's because of the changes in Devkit. @samsonasik please take a look if you can.

PRLintReloaded It requires configuration, which I do not have the necessary access to do, please do the necessary configuration.

**Comment by lonnieezell** [comment]
In the future I'd rather see all of the unrelated fixes in a separate PR. I know Rector was being a pain though. 

While I like the idea, I think in the situations I'd be using it from the command line I'd rather be able to define which role during the creation process, instead of being forced into the default and then having to go to the database to change it. 

What do you think about reading the available roles from the config file and presenting that as a required choice to the user?

**Comment by samsonasik** [comment]
@datamweb it probably related with dependabot config, 0.18.x probably only call 0.18.y, while 0.19.a need to be triggerable on specific config. CodeIgniter4 repo seems auto-update it

**Comment by datamweb** [comment]
> What do you think about reading the available roles from the config file and presenting that as a required choice to the user?

Good idea, I'd like to come back to these PR at another time.

**Comment by bgeneto** [comment]
> What do you think about reading

One can also make the `-g` argument available in the `create` action in order to set the user group otherwise use the default if not informed. This way we simplify the code and minimize the interactions while creating a new user via cli. What do you think @lonnieezell ?

**Comment by datamweb** [comment]
> PRLintReloaded It requires configuration, which I do not have the necessary access to do, please do the necessary configuration.

I send PR #1001 for add Rules.

**Comment by lonnieezell** [comment]
Sorry - forgot to reply here earlier, but PRLintReloaded is installed and should be working now.

**Comment by datamweb** [comment]
> In the future I'd rather see all of the unrelated fixes in a separate PR

I sent separates PRs for fix #1002 , #1003  and #1004 .

**Comment by kenjis** [comment]
Closed by #1162

**Pull request closed without merging**
