### PR TITLE
feat: add login link to magic link form view

### LINKED ISSUE #299: Missing back link on Magic Link form
I suggest to add a link back to the login page on the Magic Link form.
What do you think ?
CleanShot20220716142055

### PR DESCRIPTION
**Pull request by GeorgKott**
Supersedes #394
Closes #299

Thank you

### CODE REVIEW

**Review by datamweb — CHANGES_REQUESTED** [review]
@GeorgKott thank you for PR.
This issue has already been implemented in PR #394, **only the test has not been added.**

Can you do the same as PR #394 with the test?

And I edited your comment, why? you can read [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

**Comment by GeorgKott** [comment]
I did the same as PR #394, exept changing "backToLogin" key to "usePassword". And add simple test.
Thank you for edited comment

**Comment by datamweb** [comment]
> exept changing "backToLogin" key to "usePassword"

Yes, I mean using `backToLogin`. It seems to help the readability of the code. so please use `backToLogin`.

**NOTE:**
Make your commit messages meaningful.
Commit messages are important. They communicate the intent of a specific change, concisely. They make it easier to review code, and to find out why a change was made if the code history is examined later.

The audience for your commit messages will be the codebase maintainers, any code reviewers, and debuggers trying to figure out when a bug might have been introduced.

There are some references for writing good commit messages:
    [Git Best Practices — AFTER Technique - DZone DevOps](https://dzone.com/articles/git-best-practices-after-technique-1)
    [Semantic Commit Messages](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716)
    [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

more info see [here](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#committing).

**Comment by GeorgKott** [comment]
> > exept changing "backToLogin" key to "usePassword"
> 
> Yes, I mean using `backToLogin`. It seems to help the readability of the code. so please use `backToLogin`.
> 
> **NOTE:** Make your commit messages meaningful. Commit messages are important. They communicate the intent of a specific change, concisely. They make it easier to review code, and to find out why a change was made if the code history is examined later.
> 
> The audience for your commit messages will be the codebase maintainers, any code reviewers, and debuggers trying to figure out when a bug might have been introduced.
> 
> There are some references for writing good commit messages: [Git Best Practices — AFTER Technique - DZone DevOps](https://dzone.com/articles/git-best-practices-after-technique-1) [Semantic Commit Messages](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716) [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
> 
> more info see [here](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#committing).

Thank you for links! I did some changes

**Review by kenjis — APPROVED** [review]

**Comment by kenjis** [comment]
@GeorgKott Thank you!

**Pull request merged**
