### PR TITLE
lang: update sk translation

### PR DESCRIPTION
**Pull request by jozefrebjak**

### CODE REVIEW

**Comment by datamweb** [comment]
```console
1) Tests\Authentication\Authenticators\AccessTokenAuthenticatorTest::testCheckOldToken
Failed asserting that true is false.

/home/runner/work/shield/shield/tests/Authentication/Authenticators/AccessTokenAuthenticatorTest.php:136
phpvfscomposer:///home/runner/work/shield/shield/vendor/phpunit/phpunit/phpunit:[60](https://github.com/codeigniter4/shield/actions/runs/4396498069/jobs/7700037263#step:11:61)

FAILURES!
Tests: 245, Assertions: 636, Failures: 1.
```

**Review by datamweb — APPROVED** [review]
Thank you!

**Comment by kenjis** [comment]
`PHPUnit / PHP 7.4 - MySQLi - lowest (pull_request)` failed.
Why?

**Review by kenjis — APPROVED** [review]

**Comment by kenjis** [comment]
@jozefrebjak Thank you!

**Pull request merged**
