### PR TITLE
refactor: remove unused Auth::$views items

### PR DESCRIPTION
**Pull request by kenjis**
There are no such view files.

### CODE REVIEW

**Comment by datamweb** [comment]
@kenjis, Although is not related to this PR, butI think we need a change here again.
We will send emails to the user. 

```php
'action_email_2fa_email'      => '\CodeIgniter\Shield\Views\email_2fa_email'
'magic-link-email'            => '\CodeIgniter\Shield\Views\magic_link_email',
'action_email_activate_email' => '\CodeIgniter\Shield\Views\email_activate_email',
```
In fact, these three items are **HTML** formats for sending emails.
I think the following changes will be useful for readability and quick access to edit the emails text.

**suggestion:**
```php
'action_email_2fa_email'      => '\CodeIgniter\Shield\Views\Email\email_2fa_tpl'
'magic-link-email'            => '\CodeIgniter\Shield\Views\Email\magic_link_tpl',
'action_email_activate_email' => '\CodeIgniter\Shield\Views\Email\email_activate_tpl',
```

**Review by datamweb — APPROVED** [review]

**Comment by kenjis** [comment]
I think moving Email views to `Views\Email\` is good idea.
They are not Web Page views.

Do you want to change the format from HTML to plain text?

**Comment by datamweb** [comment]
> Do you want to change the format from HTML to plain text?

No, I like HTML.

**Comment by kenjis** [comment]
Okay, your suggestion is fine by me.

**Review by MGatner — APPROVED** [review]
A carryover from Myth:Auth

**Comment by datamweb** [comment]
Thanks **kenjis!**

**Pull request merged**
