### PR TITLE
Fix: register when logged in

### LINKED ISSUE #294: Registration form still accessible when user is logged in
Let's say I use the registration form to sign up: Once I've registered, I'm automatically logged in.
But then the registration form is still accessible, and I can register again and again (which creates new users and leads to an error every time).

My point is: Once a user is logged in, shouldn't the register form be closed?

I would suggest to add the following code in [src/Controllers/RegisterController.php ](https://github.com/codeigniter4/shield/blob/develop/src/Controllers/RegisterController.php#L29), at the beginning of the `registerView()` method:

```php
    ...
    public function registerView()
    {
        if (auth()->loggedIn()) {
            return redirect()->to(config('Auth')->registerRedirect());
        }

        // Check if registration is allowed
        ...
```
I can make a PR if you agree with that (actually I don't know how to proceed: should I just create an issue or directly make a PR?).

### PR DESCRIPTION
**Pull request by parisiam**
Fixes #294

- Prevents a logged in user to register
- A corresponding unit test was added

### CODE REVIEW

**Review by MGatner — CHANGES_REQUESTED** [review]
Can we get the same on `registerAction()`?

**Comment by parisiam** [comment]
Yes, sure, happy to help ;)
I've submitted the changes for registerAction() and for the tests.
Please check the tests (I may have be redundant or incomplete).

**Comment by kenjis** [comment]
What if a user is pending login state (in the process of 2FA)?
See  #132

**Comment by MGatner** [comment]
I think that's fine. They may have mistyped their email address, or want multiple accounts. In my opinion this is mostly about preventing confusion, rather than a security or behavior issue.

**Review by MGatner — APPROVED** [review]

**Review by kenjis — APPROVED** [review]
Okay, thanks!

**Pull request merged**
