### PR TITLE
fix: Shield ignores `AuthToken::$authenticatorHeader` config

### LINKED ISSUE #1168: Shield ignores `$authenticatorHeader` from AuthToken.php
### Discussed in https://github.com/codeigniter4/shield/discussions/1167

<div type='discussions-op-text'>

<sup>Originally posted by **alxjzx100** August 15, 2024</sup>
Have a feelling that I missed something, I copied this file (AuthToken.php) from vendor folder to app/Config but codeigniter ignores it. 

I tried to change the $authenticatorHeader but it has no effect. If I decare this variable at Auth.php - everything works.

What I did wrong? </div>

### PR DESCRIPTION
**Pull request by alxjzx100**
**Description**
Mentioned in discussion https://github.com/codeigniter4/shield/discussions/1167
Fixes #1168

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by datamweb** [comment]
See :

https://github.com/codeigniter4/shield/pull/672#issuecomment-1468658726
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/signing.md

**Comment by alxjzx100** [comment]
Signed, thank you.

**Comment by kenjis** [comment]
Please sign all your commits.
Screeshot 2024-08-16 11 16 37

Also, we don't like merge commits. Please do not include merge commits in PRs if you can.
You can use `git rebase` to remove the merge commit.
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#updating-your-branch

**Review by datamweb — APPROVED** [review]
LGTM!

**Review by kenjis — APPROVED** [review]

**Comment by kenjis** [comment]
@alxjzx100 Thank you!

**Pull request merged**
