### PR TITLE
chore: add no-merge-commits.yml

### PR DESCRIPTION
**Pull request by paulbalandan**
https://github.com/marketplace/actions/no-merge-commits-action

### CODE REVIEW

**Review by kenjis — APPROVED** [review]
Looks good!

**Comment by datamweb** [comment]
@paulbalandan , why do we need this feature, just to keep clean history? Or does it have other benefits?

**Comment by paulbalandan** [comment]
Why added here? I saw you guys asking contributors not use merge commits in PRs so I thought why not automate that. Yes, to keep clean history of PR once merged to develop. You don't want to see the history of `develop` having `Merge develop to ...` entries.

**Comment by datamweb** [comment]
This strictness will be useful for the repo but annoying for the contributors.
If a user uses `git merge` (see #789 ), where is it explained how he can pass **Detect Merge Commits**?
Is there an easier way than `git rebase -i` or `git cherry-pick`?

**Comment by paulbalandan** [comment]
If it is annoying, why are you enforcing it then to contributors manually (saying "Please don't use git merge, use git rebase.")? Isn't that annoying as well?

This is the behavior before and after:
BEFORE: Contributor makes a merge commits, tests all green, maintainer then remarks "don't use merge commits please"
AFTER: Contributor makes a merge commit, all tests pass except this one, it is now outright that he needs to do something to make tests green. Very little intervention needed now from maintainer. He'll just say please fix failing tests.

If you're not comfortable with this addition, please feel free to send a revert PR.

**Comment by paulbalandan** [comment]
> If a user uses `git merge` (see #789 ), where is it explained how he can pass **Detect Merge Commits**? 

Then make docs for it. I don't understand why you are making a fuss about this when this is already done in the past albeit manually. I just implemented an automated solution.

**Comment by kenjis** [comment]
> Then make docs for it. 

There is already.

I explained how to do: https://github.com/codeigniter4/shield/pull/789#issuecomment-1684371442

**Comment by kenjis** [comment]
@datamweb We added the Paul's check. But I do not expect every contributor could do `git rebase`.
So we could merge PRs with the failed check.

But I do not expect all contributors cannot use `git rebase`.
And I hope more and more contributors can use `git rebase`, because we really use it everyday,
and clean commit graph is preferable.

**Pull request merged**
