### PR TITLE
lang: [uk] Adjust translations for uk/Auth.php

### PR DESCRIPTION
**Pull request by ivanBell199**
Just a little bit of polishing for Ukrainian version of this library. I adjusted a couple of minor mistakes and changed "rememberMe" to a more typical phrase.

### CODE REVIEW

**Review by datamweb — APPROVED** [review]

**Comment by datamweb** [comment]
@ivanBell199 thanks!

**Comment by ivanBell199** [comment]
I am sorry. I was trying to add Russian localization and it was automatically added to this pull request. I am a newbie, sorry. Should I leave it like that?

**Comment by kenjis** [comment]
No, we don't accept this PR.
Could you send one for uk and another for ru?

You can send two PRs if you create another branch.
Screenshot 2023-10-30 5 30 39

For this PR, delete three last commits and force-push:
```console
$ git reset HEAD^^^
$ git push --force-with-lease origin HEAD
```

**Comment by ivanBell199** [comment]
Looks like I've figured it out. Hope it works out now. Thanks

**Comment by ivanBell199** [comment]
I have made more changes to the Ukrainian strings and added those that were not translated. This is now fully completed

**Comment by kenjis** [comment]
Sorry, you did not sign the commits.
Screenshot 2023-10-30 8 38 36

It seems you don't use `git` command.
It may be faster to close this PR and create a new one.
To be honest, we don't need the reverted commits.
This PR is simple adjustment, so one commit is enough.

**Pull request closed without merging**
