### PR TITLE
refactor: remove unneeded Entities\Cast\IntBoolCast

### PR DESCRIPTION
**Pull request by grimpirate**
**Description**
Reopening of [Pull Request #1186](https://github.com/codeigniter4/shield/pull/1186) as I deleted the repository prematurely.

### CODE REVIEW

**Comment by kenjis** [comment]
Thank you for sending this PR.
Please fix all errors in GitHub Actions.
If you have questions, feel free to ask.

**Comment by grimpirate** [comment]
@kenjis The unsuccessful checks appear to be during phpstan and rector complaining that they can no longer find the IntBoolCast and Entity classes. Those are unneeded and therefore deleted. Not sure how to fix the GitHub actions.

**Comment by kenjis** [comment]
The commit is not GPG signed. Please sign all commits.
See https://github.com/codeigniter4/shield/pull/1117#issuecomment-2118864100

**Comment by grimpirate** [comment]
@kenjis I'll have to open a new PR. I used the web editor and was trying to squash the php stan edits as I couldn't do it on the web. Sorry about that.

**Comment by kenjis** [comment]
Okay, no problem.

But I recommend you learn how to use:
- git command
- your IDE

If you learn them, you could manipulate git commits freely and easily on your local machine.
- remove existing commits and add new commits
- modify existing commits
- update your PR branch
- create multiple PRs at the same time
- check out other's PR code

**Pull request closed without merging**
