### PR TITLE
feat: add filter permission and group

### PR DESCRIPTION
**Pull request by jlopes90**
Supersedes https://github.com/codeigniter4/shield/pull/270

### CODE REVIEW

**Comment by kenjis** [comment]
> Note, we expect all code changes or bug-fixes to be accompanied by one or more tests added to our test suite to prove the code works. If pull requests are not accompanied by relevant tests, they will likely be closed. 
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#contributions

If you are not familiar with PHPUnit testing, See [Resources](https://github.com/codeigniter4/CodeIgniter4/tree/develop/tests#resources)

**Comment by jlopes90** [comment]
@kenjis @datamweb 

Sorry, I'm on vacation, I'll be back at the end of the month.  So it's better to close the pull request. Otherwise I'll delay a lot of time doing tests (phpunit) or I can't. 
So someone better make the new this PR and know how to do phpunit.

What you say?

**Comment by kenjis** [comment]
No problem. If someone really wants this feature, they would take over this PR.
You don't need to close this.

**Comment by sammyskills** [comment]
> No problem. If someone really wants this feature, they would take over this PR. You don't need to close this.

How does one take over or contribute to an existing PR? 
I tried checking online but it seems I'll need to have write access to the repository. 

Please advise.

**Comment by kenjis** [comment]
Get this PR branch into your local repository, and push it to your GitHub repository.
And create your own PR.

If you have `gh` command:
```
$ gh pr checkout 393
```
You can get this `add-filter-permission-and-group` branch.

**Comment by MGatner** [comment]
Or with just Git:
```shell
git remote add jlopez90 https://github.com/jlopez90/shield.git
git fetch jlopez90
```
You can then make a new branch starting from the existing one:
```shell
git switch -c my-takeover jlopez90/add-filter-permission-and-group
```

(I'm mobile so please excuse me if I didn't get something quiet right)

**Comment by datamweb** [comment]
In fact, I always wondered how @kenjis could handle **PR** created by others.
@MGatner Thanks! Now I learned completely.
Unfortunately, I received the following error from the mentioned method:
```shell
P:\MyGitHubWork\shield>git fetch jlopes90
fatal: unable to access 'https://github.com/jlopes90/shield.git/': OpenSSL SSL_connect: Connection was reset in connection to github.com:443
```
After a bit of research I found that setting **SSH** Key can fix the problem.
**Now it works without any problem.**
While troubleshooting I read the following:

1. [generating-a-new-ssh-key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key)
2. [adding-a-new-ssh-key-to-your-account](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account#adding-a-new-ssh-key-to-your-account)
3. [switching-remote-urls-from-https-to-ssh](https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories#switching-remote-urls-from-https-to-ssh)

I like this method, because other people's commits are not removed, and their contributions are recorded in the source. It is beautiful and fair.

**Comment by MGatner** [comment]
Yay! Glad it was helpful. Working across remotes and preserving or co-authoring work is complicated but important, and once you do it a few times it starts to feel natural.

**Comment by kenjis** [comment]
This feature seems to be needed by many, so please feel free to send new PRs based on this PR if anyone can.

**Comment by lonnieezell** [comment]
@MGatner @datamweb where do we stand on this?

**Comment by MGatner** [comment]
I don't think anyone has claimed it.

**Comment by datamweb** [comment]
[Comment 5:](https://github.com/codeigniter4/shield/pull/393#issuecomment-1263785105) I think it has caused the audience to misunderstand.
I have just done a personal practice on Git there. I did not intend to use this PR.

So anyone can continue if they want.

**Comment by lonnieezell** [comment]
Ok. I'll take this one over. It's a great start and a much needed feature.

**Comment by lonnieezell** [comment]
Superseded by #535

**Pull request closed without merging**
