### PR TITLE
Spark cli user command

### PR DESCRIPTION
**Pull request by robertogerola**
Supersedes #567,#568

With the User command is possible by cli to run these actions on users :
`'create', 'activate', 'deactivate', 'changename', 'changeemail', 'delete', 'password', 'list', 'addgroup', 'removegroup'`

Available options : 
'-i' => 'User id'
'-u' => 'User name'
'-e' => 'User email'
'-n' => 'New username'
'-m' => 'New email'
'-g' => 'Group name'

### 1. create a new user
`./spark shield:user create -u newuser -e newuser@myemail.com`

### 2. activate a user
by username : `./spark shield:user activate -u username`
or
by email : `./spark shield:user activate -e user@myemail.com`

### 3. deactivate a user
by username : `./spark shield:user deactivate -u username`
or
by email : `./spark shield:user deactivate -e user@myemail.com`

### 4. change user name
by username : `./spark shield:user changename -u username -n newusername`
or
by email : `./spark shield:user changename -e user@myemail.com -n newusername`

### 5. change user email
by username : `./spark shield:user changeemail -u username -m newuseremail@myemail.com`
or
by email : `./spark shield:user changeemail -e user@myemail.com -m newuseremail@myemail.com`

### 6. delete a user
by user id : `./spark shield:user delete -i 123`
or
by username : `./spark shield:user delete -u user`
or
by email : `./spark shield:user delete -e user@myemail.com`

### 7. change a user password
by username : `./spark shield:user password -u username`
or
by email : `./spark shield:user password -e user@myemail.com`

### 8. list users
List all users : `./spark shield:user list`
or filter by username and/or email `./spark shield:user list -u user -e user@myemail.com`

### 9. add a user to a group
by username : `./spark shield:user addgroup -u username -g mygroup`
or
by email : `./spark shield:user addgroup -e user@myemail.com -g mygroup`

### 10. remove a user from a group
by username : `./spark shield:user removegroup -u username -g mygroup`
or
by email : `./spark shield:user removegroup -e user@myemail.com -g mygroup`

All the options are optional and if the username or email are not passed on command line, a prompt will ask the user for the necessary information to complete the required task. The data inserted are validated and every operation asks for a confirmation too proceed.

### CODE REVIEW

**Comment by datamweb** [comment]
@robertogerola Thanks, can you write the **php unit test** for this PR?

**see :**
https://github.com/codeigniter4/CodeIgniter4/tree/develop/tests#resources

**Comment by kenjis** [comment]
@codeigniter4/core-team 
Is it okay the option like `-nu newusername`.
Generally an option is made of `-` and a single letter (e.g., `-n`), or `--` and word(s) (e.g. `--namespace`).

**Comment by paulbalandan** [comment]
Personally, i would choose short options with single letters and `-`, or long options with word(s) and `--`. If I'm not mistaken, from posix?, `-nu` would mean the short option `-n` followed by the value `u`, OR a combination of short options `-n` and `-u`.

**Comment by robertogerola** [comment]
Hello, just made the changes : -n for new username and -m for new email.
Regarding the request to write the unit tests, I'd need some guidance, please.
The command actions heavily rely on user input and to test these I have to simulate via MockBuilder the user input, right ?
I think it would require some effort to write the tests and due to the user input interaction I think I have to modify the code in several points and make it more complex.
Where can I find some examples how to use MockBuilder to simulate to user cli input ? I found something in the setup unit test command, but it is not very clear to me how to use it, because I have many requests of users input.
Many thanks !

**Comment by kenjis** [comment]
> The command actions heavily rely on user input and to test these I have to simulate via MockBuilder the user input, right ?

You don't need to use MockBuilder. You could use the database during testing.

Is there any command that does not need user input?
CI 4.2 does not provide a way to write tests for methods that require user input, such as CLI::prompt(), CLI::wait(), and CLI::input().

**Comment by MGatner** [comment]
Thanks for the command argument change, I think that is the correct way to handle it.

**Comment by datamweb** [comment]
> CI 4.2 does not provide a way to write tests for methods that require user input, such as CLI::prompt(), CLI::wait(), and CLI::input(). So it is difficult to write such tests.

I remember someone raised this issue, but I couldn't find PR/IS CI4 threads on GitHub.
Do you mean that we can advance this PR without testing?

**Comment by kenjis** [comment]
CI 4.3 provide a way to write tests for methods that require user input.
It seems difficult to write test for this PR without CI 4.3.

> Do you mean that we can advance this PR without testing?

It is not good to have no test at all, so if there are commands without user input, 
it is not difficult to write tests for them.

We use mocking the test target because there is no other way.
https://github.com/codeigniter4/shield/blob/44bbf2c88128deae72dad5bc5becb4010d234bb4/tests/Commands/SetupTest.php#L44-L50
But I don't think it is good practice. Because mock is not a true product code.

**Comment by kenjis** [comment]
CI 4.3 was released, so you can write tests for CLI input.
https://codeigniter4.github.io/CodeIgniter4/testing/overview.html#testing-cli-input

I think we can skip the tests for CI 4.2 and below.

**Review by cijagani — APPROVED** [review]

**Comment by kenjis** [comment]
> CI 4.3 was released, so you can write tests for CLI input.
https://codeigniter4.github.io/CodeIgniter4/testing/overview.html#testing-cli-input

It was wrong. 4.3 is not enough to write tests for this command.
I rewrite the command to improve testability. See #833

**Comment by kenjis** [comment]
Closed by #833

**Pull request closed without merging**
