### PR TITLE
lang: [tr]&[uk] fix Invalid param in `errorPasswordPwned`

### PR DESCRIPTION
**Pull request by datamweb**
**Description**
ref: #953 

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by datamweb** [comment]
@paulbalandan If you can check this topic and add it to
`Language Unit Test`, it will be great.

**Comment by paulbalandan** [comment]
I'm sorry I don't get what you mean. What do you want me to do?

**Comment by datamweb** [comment]
This is the original text:
```php
'errorPasswordPwned' => 'The password {0} has been exposed due to a data breach and has been seen {1, number} times in {2} of compromised passwords.',
```

This text has been translated into another language, unfortunately **number** ({1, number}) have been translated in this field, which causes failure.
```php
'errorPasswordPwned' => '{0} şifresi, bir veri ihlali nedeniyle açığa çıktı ve güvenliği ihlal edilmiş şifrelerin {2} tanesinde {1, sayı} kez görüldü.',
```

In fact, we did not realize this during the merger. Now I want to see if you can check by **Language Unit Test** that strings like (({1, number})) should not be translated.

**Review by kenjis — APPROVED** [review]

**Comment by kenjis** [comment]
Ref https://codeigniter4.github.io/CodeIgniter4/outgoing/localization.html#replacing-parameters

**Comment by paulbalandan** [comment]
Ok, I get it. I'll check what I can do.

**Pull request merged**
