### PR TITLE
chore: add resolving a merge conflict to smart-commenting

### PR DESCRIPTION
**Pull request by datamweb**
**Description**
Explain what you have changed, and why.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
@datamweb I have never used GitHub "Resolve conflicts". But doesn't it make a merge commit?

> Warning: When you resolve a merge conflict on GitHub, the entire [base branch](https://docs.github.com/en/get-started/quickstart/github-glossary#base-branch) of your pull request is merged into the [head branch](https://docs.github.com/en/get-started/quickstart/github-glossary#head-branch). Make sure you really want to commit to this branch. If the head branch is the default branch of your repository, you'll be given the option of creating a new branch to serve as the head branch for your pull request. If the head branch is protected you won't be able to merge your conflict resolution into it, so you'll be prompted to create a new head branch. For more information, see "[About protected branches](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches)."
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

**Comment by paulbalandan** [comment]
Yes, using GitHub's resolve conflict button will result in a merge commit

**Comment by datamweb** [comment]
I deleted Github way.

**Review by paulbalandan — APPROVED** [review]

**Comment by kenjis** [comment]
@datamweb Do you think the link to GitHub site helps contributors?

Conflicts occur as a result of updates to the `develop`. 
So we need to `git rebase` the PR branch, and during the rebase the conflicts will occur.
However, the GitHub page explains how to deal with conflicts after they occur.

I think the explanation of running `git rebase` is missing.

**Comment by datamweb** [comment]
> Do you think the link to GitHub site helps contributors?

I answer your answer with a question. Why is there such a link if it is not useful?

The truth is, I never knew what Git was when I made my first contribution to GitHub. After thousands of your tips I realized I was missing something(git cli). Does everyone follow up like me to learn, sure that a large percentage will give up.

Whether we like it or not, we have to accept that using this tool is normal for team, but is it the same for all contributors? 
My answer, no.

Finally, I think a large percentage of people are more comfortable with Github GUI.

**Review by kenjis — APPROVED** [review]
Nobody comments.
The workflow in the CI4 repository does not work, so I merge this for now.

**Pull request merged**
