### PR TITLE
feat: add allow to cancel actions for custom cases

### PR DESCRIPTION
**Pull request by datamweb**
Hello friends.
The purpose of these PR,
Add a feature to cancel actions if there are custom cases. 
This PR allows the shield to cancel actions by checking the user `groups`,`permissions `or `userID`.

Task checklist:
- [x] Add to docs
- [x] Edit `Session::class`
- [ ] Add test

### CODE REVIEW

**Comment by datamweb** [comment]
Guys, if you agree with these **PR** in general, please let me know so I can complete the test as well.

**Comment by kenjis** [comment]
Why do you need this feature?
Use cases?

**Comment by datamweb** [comment]
- The ability to manage resources (management of server resources for sending emails, managing financial resources for sending SMS fees)
- Non-engagement of unfamiliar users with new topics (2fa)

Two-step login for users with low access level is **not necessary** in many cases and it causes **financial cost or filling the ceiling of email sending limits**, but it **is very important** for **users with high access level even** though it is expensive.
Therefore, by canceling actions for groups with low access level, it has helped a lot in this regard.

I believe that the actions in the shield are very useful, but they need to be changed. for example
Why don't the codes sent by actions expire?
Why is it not possible to define multiple actions for one type of action?
Why is it not possible to order the length of the sent code (usually 4 digits are used in SMS)
Why don't we have an action called `Google2FA`, even though it is very popular?
All these things can be implemented, but why does the shield not support them by default?

**Comment by datamweb** [comment]
I will close this issue, if a user needed this PR, we should have received a feedback by now.

**Comment by kenjis** [comment]
I think if an action is to be disabled only for specific users, it is better to make it configurable for that action, rather than disabling all actions.

**Comment by datamweb** [comment]
That's right, so each user can write their own [custom action](https://github.com/datamweb/shield/blob/develop/docs/auth_actions.md#defining-new-actions) if needed.

**Pull request closed without merging**
