### PR TITLE
fix: add missing `Auth.registerSuccess` for farsi

### PR DESCRIPTION
**Pull request by datamweb**
Hi,
related to PR: #169

### CODE REVIEW

**Comment by kenjis** [comment]
This is not must for this PR, but it seems your `develop` is out of dated.
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#syncing-develop

And how to update the PR branch:
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#pushing-your-branch

**Comment by kenjis** [comment]
> But I do not know why GitHub Action still gets errors!

We don't know why. It is GitHub authentication error.

```
Error: Could not authenticate against github.com
                                             
  [Composer\Downloader\TransportException]   
  Could not authenticate against github.com  
```

**Review by kenjis — APPROVED** [review]

**Review by lonnieezell — APPROVED** [review]

**Comment by MGatner** [comment]
A contributing factor could be that we still have the repository listed in **composer.json** even though we don't need it anymore:
```json
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/codeigniter4/CodeIgniter4"
        }
    ],
```
This might be triggering an unnecessary pull which adds a point of failure.

**Comment by kenjis** [comment]
We don't use `codeigniter4/codeigniter4` here, so I think the `repositories` item does not matter.

**Comment by MGatner** [comment]
Composer doesn't know what the repository contains until it fetches **composer.json** from it, so I believe it will be polled on every update even if we aren't using it.

**Comment by MGatner** [comment]
I tried creating a PR from mobile: https://github.com/codeigniter4/shield/pull/178

Never done that before, hopefully it worked.

**Comment by kenjis** [comment]
> Composer doesn't know what the repository contains until it fetches composer.json from it, so I believe it will be polled on every update even if we aren't using it.

Yes.

```
Loading composer repositories with package information
Using GitHub token authentication
Downloading https://api.github.com/repos/codeigniter4/CodeIgniter4
[200] https://api.github.com/repos/codeigniter4/CodeIgniter4
Downloading https://api.github.com/repos/codeigniter4/CodeIgniter4/contents/composer.json?ref=develop
[200] https://api.github.com/repos/codeigniter4/CodeIgniter4/contents/composer.json?ref=develop
Downloading https://api.github.com/repos/codeigniter4/CodeIgniter4/commits/develop
[200] https://api.github.com/repos/codeigniter4/CodeIgniter4/commits/develop
Downloading https://api.github.com/repos/codeigniter4/CodeIgniter4/contents/.github/FUNDING.yml
[404] https://api.github.com/repos/codeigniter4/CodeIgniter4/contents/.github/FUNDING.yml
Downloading https://api.github.com/repos/codeigniter4/.github/contents/FUNDING.yml
[404] https://api.github.com/repos/codeigniter4/.github/contents/FUNDING.yml
Downloading https://api.github.com/repos/codeigniter4/CodeIgniter4/tags?per_page=100
[200] https://api.github.com/repos/codeigniter4/CodeIgniter4/tags?per_page=100
```

> So yes, it is not required but could still be affecting our authentication errors.

Might be.

**Comment by MGatner** [comment]
I wonder if those 404 are actually part of the problem?

**Pull request merged**
