### PR TITLE
fix: bootstrap column on mobile device

### PR DESCRIPTION
**Pull request by MitkoIT**

### CODE REVIEW

**Comment by datamweb** [comment]
Hello @MitkoIT, 
Please send a screenshot of before and after this PR.
Thank you.

**Comment by MitkoIT** [comment]
before
image

**Comment by MitkoIT** [comment]
after 
image

**Comment by datamweb** [comment]
Please apply these changes in `src\Views\email_activate_show.php`.

**Comment by kenjis** [comment]
I've confirmed the current broken page:
Screenshot 2022-08-12 18 37 54

**Comment by MitkoIT** [comment]
@datamweb done ;)

**Review by datamweb — APPROVED** [review]
I'm fine by PR, we already made these changes in #287 .

**Review by kenjis — APPROVED** [review]

**Review by MGatner — APPROVED** [review]
Thanks @MitkoIT

**Pull request merged**
