### PR TITLE
fix: use named routes for redirects and form submission

### LINKED ISSUE #879: Bug: Bad redirection in the registration process (auth/a/show and auth/a/verify)
### PHP Version

8.2.10

### CodeIgniter4 Version

4.4.1

### Shield Version

1.0.0-beta.6

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB 11.1

### Did you customize Shield?

No

### What happened?

When the shield routes are defined as following:
```php
  $routes->group('{locale}/account', static function($routes) {
    service('auth')->routes($routes);
  });
```
some URLS are not generated correctly in the registration process:
* https://glossary.local/glossary/auth/a/show instead of https://glossary.local/glossary/fr/account/auth/a/show
* https://glossary.local/glossary/auth/a/verify instead of https://glossary.local/glossary/fr/account/auth/a/verify

### Steps to Reproduce

1. Rewrite the shield routes to include locale and a top level
2. Try to register a new user

### Expected Output

Correct redirection and form submitted to the right URL.

### Anything else?

A possible solution is to make a fix in two files:
* In Controllers\RegistrerController.php:
change: return redirect()->to('auth/a/show');
into:      return redirect()->route('auth-action-show');
* In Views\email_activate_show.php
change: &lt;form action="&lt;?= site_url('auth/a/verify') ?&gt;" method="post"&gt;
into:      &lt;form action="&lt;?= url_to('auth-action-verify') ?&gt;" method="post"&gt;

### PR DESCRIPTION
**Pull request by sammyskills**
**Description**
- Used named route for redirect in the **src/Controllers/RegisterController.php** file
- Used named route for form action in **src/Views/email_action_show.php** file.

Fixes #879 

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by kenjis — APPROVED** [review]
LGTM!

**Comment by kenjis** [comment]
@datamweb What is the docs?
I would like to merge this and release beta7 soon.

**Comment by sammyskills** [comment]
I was also wondering why @datamweb added the docs label 🤷‍♂️

**Comment by datamweb** [comment]
Guys, 
It was not possible to use this method before, I know that there are people looking for this feature in the forum and even in the Github discussion, so it is better to add how to use this feature in the documents.

But I have a question, why do I face page 404 after using the following address?

```php
$routes->group('{locale}', static function($routes) {
service('auth')->routes($routes);
});
```
localhost::8080/ja/login (is ok)

localhost::8080/login (404)
I would expect it to load with the default language set if no language is specified, not a 404 page. It is probably related to the framework? 

Outside of this I feel it needs more investigation, about how to use filters and more.

In any case, 
I don't have access to a PC right now, if you think there is ok, continue.

**Comment by sammyskills** [comment]
@datamweb, this is not a new feature. It is just a fix to make Shield routes less fragile by using named routes all through the codebase. Please read the issue #879 if you haven't read it already.

>localhost::8080/login (404)
I would expect it to load with the default language set if no language is specified, not a 404 page. It is probably related to the framework?

What you are saying here (I think) is related to how you set up your locale to be detected. From the [docs](https://codeigniter4.github.io/CodeIgniter4/outgoing/localization.html#locale-detection):
>There are two methods supported to detect the correct locale during the request. The first is a “set and forget” method that will automatically perform [content negotiation](https://codeigniter4.github.io/CodeIgniter4/incoming/content_negotiation.html) for you to determine the correct locale to use. The second method allows you to specify a segment in your routes that will be used to set the locale.

If you have set the locale using routes, then the system should be expecting `localhost:8080/en/login` assuming that your default locale is `en`.

Please try running the `php spark routes` command to see the available routes.

**Comment by kenjis** [comment]
@datamweb 
`{locale}` in a route is just a wild card. It will be interpreted as the regex `[^/]+`.

```php
$routes->group('{locale}', static function($routes) {
    service('auth')->routes($routes);
});
```

```
+--------+----------------------------------+--------------------+--------------------------------------------------------------------+----------------+---------------+
| Method | Route                            | Name               | Handler                                                            | Before Filters | After Filters |
+--------+----------------------------------+--------------------+--------------------------------------------------------------------+----------------+---------------+
| GET    | /                                | »                  | \App\Controllers\Home::index                                       | session        | toolbar       |
| GET    | {locale}/register                | register           | \CodeIgniter\Shield\Controllers\RegisterController::registerView   | session        | toolbar       |
| GET    | {locale}/login                   | login              | \CodeIgniter\Shield\Controllers\LoginController::loginView         | session        | toolbar       |
| GET    | {locale}/login/magic-link        | magic-link         | \CodeIgniter\Shield\Controllers\MagicLinkController::loginView     | session        | toolbar       |
| GET    | {locale}/login/verify-magic-link | verify-magic-link  | \CodeIgniter\Shield\Controllers\MagicLinkController::verify        | session        | toolbar       |
| GET    | {locale}/logout                  | logout             | \CodeIgniter\Shield\Controllers\LoginController::logoutAction      | session        | toolbar       |
| GET    | {locale}/auth/a/show             | auth-action-show   | \CodeIgniter\Shield\Controllers\ActionController::show             | session        | toolbar       |
| POST   | {locale}/register                | register           | \CodeIgniter\Shield\Controllers\RegisterController::registerAction | session        | toolbar       |
| POST   | {locale}/login                   | »                  | \CodeIgniter\Shield\Controllers\LoginController::loginAction       | session        | toolbar       |
| POST   | {locale}/login/magic-link        | »                  | \CodeIgniter\Shield\Controllers\MagicLinkController::loginAction   | session        | toolbar       |
| POST   | {locale}/auth/a/handle           | auth-action-handle | \CodeIgniter\Shield\Controllers\ActionController::handle           | session        | toolbar       |
| POST   | {locale}/auth/a/verify           | auth-action-verify | \CodeIgniter\Shield\Controllers\ActionController::verify           | session        | toolbar       |
+--------+----------------------------------+--------------------+--------------------------------------------------------------------+----------------+---------------+
```

**Comment by kenjis** [comment]
@datamweb I sent a PR for docs: #884

**Comment by datamweb** [comment]
@sammyskills and @kenjis  thank you!

**Pull request merged**
