### PR TITLE
Add French translations

### PR DESCRIPTION
**Pull request by ThibautPV**
If @includebeer sees any changes to be made, don't hesitate.

### CODE REVIEW

**Comment by datamweb** [comment]
Hi @ThibautPV , please check:
https://github.com/codeigniter4/shield/pull/235#issuecomment-1153050805

**Comment by ThibautPV** [comment]
Hi @datamweb 

Can you tell me if it's ok now please?

It's seem some checks were not successful..

**Comment by datamweb** [comment]
All code must conform to our Style Guide, which is based on **PSR-12**.
You can fix most of the coding style violations by running this command in your terminal:

@ThibautPV  **So just run**:
```console
> composer cs-fix
```
Note : If you are interested to know more, please read [CodeIgniter Coding Style Guide](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#php-style).

**Comment by ThibautPV** [comment]
Ok perfect :) 

Thanks @datamweb

**Comment by datamweb** [comment]
@ThibautPV Oh! you have **not** translated the **latest version of the language file**.
The latest version of the language file is [here](https://github.com/codeigniter4/shield/blob/develop/src/Language/en/Auth.php).
please check it.

**Comment by ThibautPV** [comment]
@datamweb : Pfff... Sorry...

I think it's ok now

**Comment by includebeer** [comment]
@ThibautPV look mostly fine to me. I think you forgot to translate this key: **suggestPasswordLength**

**Comment by kenjis** [comment]
Yes, `suggestPasswordLength` test fails.

```consloe
$ composer test
> phpunit
PHPUnit 9.5.21 #StandWithUkraine

Runtime:       PHP 8.0.20
Configuration: /Users/kenji/work/codeigniter/codeigniter-shield/phpunit.xml
Random Seed:   1656797994

...............F...............................................  63 / 199 ( 31%)
............................................................... 126 / 199 ( 63%)
............................................................... 189 / 199 ( 94%)
..........                                                      199 / 199 (100%)

Nexus\PHPUnit\Extension\Tachycardia identified these 3 slow tests:
+--------------------------------------------------------------------------+---------------+-------------+
| Test Case                                                                | Time Consumed | Time Limit  |
+--------------------------------------------------------------------------+---------------+-------------+
| Tests\\Controllers\\RegisterTest::testRegisterActionSuccess              | 00:00:00.94   | 00:00:00.50 |
| Tests\\Controllers\\RegisterTest::testRegisterRedirectsToActionIfDefined | 00:00:00.93   | 00:00:00.50 |
| Tests\\Unit\\DictionaryValidatorTest::testCheckTrueOnNotFound            | 00:00:00.82   | 00:00:00.50 |
+--------------------------------------------------------------------------+---------------+-------------+


Time: 00:13.260, Memory: 42.00 MB

There was 1 failure:

1) Tests\Language\FrenchTranslationTest::testAllIncludedLanguageKeysAreTranslated with data set "fr" ('fr')
Failed asserting that the translated language key "Auth.suggestPasswordLength" in "fr" locale differs from the original keys in the main repository.
Failed asserting that an array is empty.

/Users/kenji/work/codeigniter/codeigniter-shield/tests/Language/AbstractTranslationTestCase.php:255

FAILURES!
Tests: 199, Assertions: 462, Failures: 1.
Script phpunit handling the test event returned with error code 1
```

**Comment by ThibautPV** [comment]
@includebeer @kenjis : Thanks for your feedback

It's fixed :)

**Review by kenjis — APPROVED** [review]

**Comment by datamweb** [comment]
Thanks to everyone for improving this PR.
@ThibautPV **Merci beaucoup**.

**Review by MGatner — APPROVED** [review]
Ça fait longtemps que j'ai étudié le français! Ça marche bien.

**Comment by datamweb** [comment]
@ThibautPV The subject of this PR is **Add French translations**. All the work related to the translation has been done correctly, and the **two main members of this PR have confirmed**.

Commit [e70f4fb](https://github.com/codeigniter4/shield/pull/272/commits/e70f4fbd7990da56abc0a1408ebf56b26003f510) is **unrelated to this PR**. Therefore, you should submit the changes related to commit [e70f4fb](https://github.com/codeigniter4/shield/pull/272/commits/e70f4fbd7990da56abc0a1408ebf56b26003f510) in the **new PR**.

 **A reminder:** please use separate branches for each of your PRs - it will make it easier for you to keep changes separate from each other and from whatever else you are doing with your repository!

One thing at a time: A pull request should only contain one change. That does not mean only one commit, but one change - however many commits it took. The reason for this is that if you change X and Y, but send a pull request for both at the same time, we might really want X but disagree with Y, meaning we cannot merge the request. Using the Git-Flow branching model you can create new branches for both of these features and send two requests.
Note : please read [Branching](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#branching)

**Comment by ThibautPV** [comment]
Hi @datamweb ,

Sorry, I've never used Git before.

Can you tell me if it's ok now?

**Comment by kenjis** [comment]
@ThibautPV Thank you!

**Comment by datamweb** [comment]
> Sorry, I've never used Git before.
> 

@ThibautPV **no problem**. We have all made these mistakes just like you. I am a beginner in git.
Recently, with the help of @kenjis , I have been on the path of learning it.
Also, don't worry, everyone here will help you to get on the right track to learn it according to the level of expertise and free time they have, **you just need to be interested**.

[Here ](https://github.com/progit/progit2-fr/releases/download/2.1.70/progit.pdf)is a very good book that helped me a lot.
Also [here ]( https://git-scm.com/book/fr/v2)is the Git documentation in **French**.
 I suggest you start with it and the **videos on YouTube**.

At this stage, learn the following commands:
```console
git config
git status
git remote
git branch
git switch
git add
git commit
git diff
git log
git log --oneline
git reset
git restore
git reset HEAD
git checkout
git push
```
> Can you tell me if it's ok now?

Everything went well. And this PR is merged.

**Comment by ThibautPV** [comment]
Thank you very much for these clarifications 👍

**Pull request merged**
