### PR TITLE
bug: fix magic_link_message view template

### PR DESCRIPTION
**Pull request by sammyskills**
Removed unnecessary ending form tag from `magic_link_message.php`

### CODE REVIEW

**Review by MGatner — APPROVED** [review]
Thanks! Not sure how that got there 🤔

**Comment by sammyskills** [comment]
Just out of curiosity, can we have the hacktoberfest label in this repo, so it can be seen as a participating repo?

**Review by datamweb — CHANGES_REQUESTED** [review]
@sammyskills Your PR has changed 5 files. Please change only file `src/Views/magic_link_message.php`.
It also looks like you need to [Syncing Your Repository](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#syncing-your-repository) and then run command ``composer update``, but it's not necessary for this PR.

**Comment by sammyskills** [comment]
Yes @datamweb, I ran `composer cs-fix` after making the change on the affected file.

Is there a way I can undo this?

**Comment by MGatner** [comment]
Re: Hacktoberfest... I looked over our issues and I don't know that this repo would be very accessible to random visitors. I would rather direct any CodeIgniter-curious do-gooders to the framework repo where we have more "one-off" issues.

**Comment by MGatner** [comment]
@sammyskills you can reset your commit with `git reset HEAD~1` and then add back only the files you want: `git add foo.php bar/bam.js` and just commit that subset. You will need to force your changes to the remote: `git push -f`. After that if you don't need any other the other changes you can restore them: `git restore .` (and if there are new files, `git clean -fd`). Those last two commands are destructive so be sure you double-check your work.

**Comment by datamweb** [comment]
> Yes @datamweb, I ran `composer cs-fix` after making the change on the affected file.

If you used the **atomic commit** method, now you could easily return to the desired commit. But you can't here.


> Is there a way I can undo this?
```shell 
git switc update-magic-link-template
git branch -m update-magic-link-template old-update-magic-link-template
git switch -c update-magic-link-template develop
code .
```


After that, change `src/Views/magic_link_message.php`
```shell
git commit -m "Removed unnecessary ending form tag from magic_link_message view "
git push -f origin update-magic-link-template
```
I suggest you use method [atomic commit](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#committing) after this.

**Comment by sammyskills** [comment]
Hi @datamweb ,

I have followed your steps and pushed the changes, but still get some errors. 

Ia this the right time to run `composer cs-fix` ?

**Comment by datamweb** [comment]
@sammyskills In my opinion, my method did not work well. Method @MGatner' was interesting.
Let's try to see if it works.
```shell
git branch -m update-magic-link-template old2-update-magic-link-template
git branch -m old-update-magic-link-template update-magic-link-template 
git reset HEAD~1
git add src/Views/magic_link_message.php
git commit -m "Removed unnecessary ending form tag from magic_link_message"
git push -f origin update-magic-link-template
```

**Comment by datamweb** [comment]
> Just out of curiosity, can we have the hacktoberfest label in this repo, so it can be seen as a participating repo?
> 
I'm generally good with anything that motivates and encourages developers.
Encouraging people works wonders.
I'm sure I would never be here if it wasn't for the encouragement of Kenji and the others. He encouraged me and I tried to get better.
So I'm fine with adding this tag.
See what other members have to say.

**Comment by datamweb** [comment]
@sammyskills Your commit is not signed. 
Please see [GPG-Signing Old Commits](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#gpg-signing-old-commits)

**Review by datamweb — APPROVED** [review]
Thanks👌.

**Comment by kenjis** [comment]
Re: Hacktoberfest, I am okay that this repository also participates Hacktoberfest.
It may encourage who are using this library to send PRs.

**Review by kenjis — APPROVED** [review]

**Pull request merged**
