### PR TITLE
fix: Debugbar error after logout 

### LINKED ISSUE #210: Call to a member function getGroups() on null
I point out that when the logout is performed, an error occurs in the development environment with the toolbar active, as shown in the attached image. In production environment or disabling the toolbar the error does not appear.

error

### PR DESCRIPTION
**Pull request by kenjis**
Fixes #210

- fix: update `$this->userState` when logout
- remove unneeded helper loading

### CODE REVIEW

**Review by MGatner — APPROVED** [review]

**Comment by datamweb** [comment]
Thanks @kenjis  works well now.

**Comment by kenjis** [comment]
When I tried to reproduce the bug in #210, I could not reproduce it, and since the error was not displayed, 
I thought that it was not a bug.
But @datamweb reproduces the error, and I looked the code again, it must be a bug.
I don't know why I did not see the error.

So I changed this PR subject, and a commit message.

**Comment by datamweb** [comment]
I suggest you add the following test:

```
public function testDisplayNotLoggedInAfterLogout(): void
{
        $authenticator = service('auth')->getAuthenticator();
        assert($authenticator instanceof Session);
        $authenticator->login($this->user);
        
        $authenticator->logout($this->user);

        $output = $this->collector->display();
        $this->assertStringContainsString('Not logged in', $output);
}
```

unittest

**Review by lonnie-vault — APPROVED** [review]

**Review by MGatner — APPROVED** [review]
I love the collaboration! Thanks to all.

**Pull request merged**
