### PR TITLE
Added revokeAccessTokenBySecret

### PR DESCRIPTION
**Pull request by WaaaghNL**
**Description**
After losing some tokens while i developed my app and i didnt want to remove all of the tokens i changed the `revokeAccessToken` to support removeing them by the secret that you can get with the `AccessTokens()` function.

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by kenjis — APPROVED** [review]

**Comment by WaaaghNL** [comment]
I saw it, still figuring out git. My bad sorry

**Comment by WaaaghNL** [comment]
@kenjis i think that i'm missing something. What kind of information are we waiting for?

**Comment by datamweb** [comment]
@WaaaghNL currently, this public relations is conflicting.
You need to update your branch and fix the conflict.
If you don't know how to use Git well, you can send a new PR.

**Comment by kenjis** [comment]
Yes, update your PR branch and resolve the conflicts.
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#updating-your-branch

**Pull request closed without merging**
