### PR TITLE
docs: fix definition actions

### PR DESCRIPTION
**Pull request by datamweb**
**Hello friends**, we have already presented the definition of actions in this way:
```php
public array $actions = [
    'login'    => 'CodeIgniter\Shield\Authentication\Actions\Email2FA',
    'register' => 'CodeIgniter\Shield\Authentication\Actions\EmailActivator',
];
```
Or it can be as follows
```php
public array $actions = [
    'login'    => \CodeIgniter\Shield\Authentication\Actions\Email2FA::class,
    'register' => \CodeIgniter\Shield\Authentication\Actions\EmailActivator::class,
];
```
In any case, correction was needed.

### CODE REVIEW

**Review by kenjis — APPROVED** [review]

**Review by MGatner — APPROVED** [review]
I prefer the shortname with `::class` to make the class names explicit (also ensures static analysis knows these are classes) but for docs this is probably good.

**Comment by datamweb** [comment]
I also agree with shortname with `::class`, if other members also agree, I can apply changes in this PR based on what @MGatner said.

**Comment by kenjis** [comment]
It is recommended to use `::class` always.

**Comment by kenjis** [comment]
This is a bug in the docs. So I merged.
Welcome another PR to use `::class`.

**Pull request merged**
