### PR TITLE
docs: update out-of-dated sample code for `syncGroups()`

### PR DESCRIPTION
**Pull request by kenjis**

### CODE REVIEW

**Comment by datamweb** [comment]
@kenjis , I had made this mistake once before.
In your opinion, supporting both modes (`string `or `array`) of parameters is not better?

eg: 

```php
$user->syncGroups(['admin', 'beta']);
$user->syncGroups('admin', 'beta');

$user->inGroup(['superadmin', 'admin']);
$user->inGroup('superadmin', 'admin');

$user->addPermission(['users.create', 'users.edit']);
$user->addPermission('users.create', 'users.edit');
```

**Comment by kenjis** [comment]
See https://github.com/codeigniter4/shield/blob/d234619a688f99d1f6cff3b1c08b9d5f63fb6bb9/src/Authorization/Traits/Authorizable.php#L83
Now it is typed as `string`. You don't mistake if you are using IDE.
Screenshot 2022-07-04 13 25 51

**Comment by kenjis** [comment]
In my opinion, supporting both types brings unnecessary complexity in the implementation.

If you really love arrays, you can write like this:
```php
$user->syncGroups(...['admin', 'beta']);
```

**Comment by datamweb** [comment]
Thanks @kenjis , it was very interesting.

**Comment by jozefrebjak** [comment]
@kenjis  Please add real world example with form input data , till the update we synced groups like this:

```php
// Save the user's groups
$user->syncGroups($this->request->getPost('groups') ?? []);
```

What is the best way to handle this now ?

**Comment by kenjis** [comment]
It causes an error when `$this->request->getPost('groups')` returns null.

**Comment by jozefrebjak** [comment]
> It causes an error when `$this->request->getPost('groups')` returns null.

So we need to use it like this:

```php
 $user->syncGroups(...$this->request->getPost('groups') ?? []);
```

**Comment by MGatner** [comment]
> supporting both modes (`string` or `array`) of parameters is not better?

One of the greatest strengths of variadic parameters is that they can be strongly-typed, which is especially appealing since PHP cannot specify collective types like "an array of strings" without PHPDoc `string[]` or `array<string>`. Enforcing the variadic version will help IDEs (as kenjis noted) and static analysis, and catch mistakes that might be overlooked otherwise.

**Comment by MGatner** [comment]
> So we need to use it like this

@jozefrebjak I don't think that will work because the splat operator will try to resolve before the null coalescence. I would just use an intermediate variable, though if you really wanted a single line you might be able to use parentheses to specify the ordering.

**Comment by MGatner** [comment]
Actually I just tried it an it does work! https://3v4l.org/G3qOZ

Who knew 🤭

**Review by MGatner — APPROVED** [review]

**Comment by kenjis** [comment]
This works without any problem:
```php
$user->syncGroups(...$this->request->getPost('groups') ?? []);
```
But I feel it is a bit long and difficult to read.
I prefer to use an intermediate variable:
```php
$groups = $this->request->getPost('groups') ?? [];
$user->syncGroups(...groups);
```

**Pull request merged**
