### PR TITLE
docs: add Session Authenticator Event and Logging

### PR DESCRIPTION
**Pull request by kenjis**
From #131

### CODE REVIEW

**Review by MGatner — APPROVED** [review]
Very helpful!

**Comment by datamweb** [comment]
Just one suggestion, it will be more beautiful with [Markdown Mermaid](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/)

**Comment by kenjis** [comment]
@datamweb I'm not sure Mermaid can improve this document. 
What diagram?

**Comment by datamweb** [comment]
Ok @kenjis, I will do it if necessary.

Only we have listed all the files in `index.md`, do we need to add this file?

**Comment by kenjis** [comment]
> Only we have listed all the files in index.md, do we need to add this file?

I don't think so. If we does so, when the number of files increases too much, it becomes difficult to find them.

**Pull request merged**
