### PR TITLE
refactor: updateActiveDate query builder

### PR DESCRIPTION
**Pull request by kpeu3u**

### CODE REVIEW

**Comment by kenjis** [comment]
Sorry, what's the point?

**Review by MGatner — APPROVED** [review]
The method does a lot more bootstrapping than just accessing the property. It also isn't `final` so it is possible someone is extending it for additional behavior. 

I'm good with this change.

**Comment by datamweb** [comment]
Hello,
Your commit is not signed, please check the following to sign it.

See :
[Adding A GPG Key To Your Github Account](https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account)
[GPG Signing Old Commits](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#gpg-signing-old-commits)

**Comment by kenjis** [comment]
And improving the commit message is welcome.

> Commit messages are expected to be descriptive of why and what you changed specifically. Commit messages like "Fixes #1234" would be asked by the reviewer to be revised.
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#commit-messages

**Comment by datamweb** [comment]
Please pay attention to what Kenjis said. 
https://github.com/codeigniter4/shield/pull/520#issuecomment-1312416407

**Review by kenjis — CHANGES_REQUESTED** [review]
Commit messages are important. They communicate the intent of a specific change, concisely. They make it easier to review code, and to find out why a change was made if the code history is examined later.

The audience for your commit messages will be the codebase maintainers, any code reviewers, and debuggers trying to figure out when a bug might have been introduced.

Make your commit messages meaningful.

Commit messages are expected to be descriptive of **why** and what you changed specifically. Commit messages like "Fixes #1234" would be asked by the reviewer to be revised.

**Review by MGatner — APPROVED** [review]

**Review by datamweb — APPROVED** [review]

**Comment by MGatner** [comment]
@kenjis Waiting on you

**Review by kenjis — APPROVED** [review]

**Comment by kenjis** [comment]
Thank you all.

**Pull request merged**
