### PR TITLE
docs: reorganize (part 3/3)

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
See #841

- split Authentication page
- move "Session Authenticator Event and Logging" in "Session Authenticator"
- add links to References

Screenshot 2023-09-22 17 54 46

Online Demo : https://datamweb.github.io/shield/

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [x] User guide updated
- [] Conforms to style guide

### CODE REVIEW

**Review by datamweb — APPROVED** [review]

**Comment by kenjis** [comment]
Added `content.code.copy`.

**Review by datamweb — APPROVED** [review]
Thank you!

**Comment by datamweb** [comment]
@kenjis Can you create a subdomain as below so that documents are available with the subdomain.
https://shield.codeigniter.com/

Demo https://www.shield-oauth.codeigniter4.ir/

**Comment by kenjis** [comment]
No, I can't.
@lonnieezell @MGatner ?

**Comment by datamweb** [comment]
Guys, if you did, please don't forget to register a CNAME (codeigniter4.github.io) for the subdomain.

**Comment by MGatner** [comment]
I will look into it - got a fair amount of website work that needs doing on there first.

**Comment by kenjis** [comment]
Yes, updating the official website is a top priority.
https://github.com/codeigniter4projects/website/pull/396#issuecomment-1712476977

**Comment by MGatner** [comment]
The website looks like it is updated correctly. I got my key fixed and there are a lot of updates we should run on the box soon, but I will wait and coordinate with @lonnieezell

**Pull request merged**
