### PR TITLE
docs: separation for ease of command copying

### PR DESCRIPTION
**Pull request by datamweb**
**Description**
Explain what you have changed, and why.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
If I copy the block now, I can paste the following. And no problem.
```
composer config minimum-stability dev
composer config prefer-stable true
```
Screenshot 2023-10-20 9 09 34

**Comment by datamweb** [comment]
I get a warning in Windows. That I must always confirm.

Screenshot 2023-10-20 001834

**Comment by paulbalandan** [comment]
@datamweb what terminal are you using?

**Comment by datamweb** [comment]
Windows PowerShell/cmd,
It does not differ, in both. 

https://github.com/codeigniter4/shield/assets/9530214/108ffa81-3783-4101-aa32-6e5cc410656c

**Comment by paulbalandan** [comment]
try this: https://superuser.com/questions/1677982/how-do-i-get-windows-terminal-to-stop-asking-me-every-time-i-paste-something-int

I'm using the integrated terminal on vscode so it's not a problem for me. but confirmed this as behavior of Windows Terminal.

**Comment by datamweb** [comment]
> try this: https://superuser.com/questions/1677982/how-do-i-get-windows-terminal-to-stop-asking-me-every-time-i-paste-something-int

Thank You! It worked well.

**Pull request closed without merging**
