### PR TITLE
chore: add multiple db platforms in GA workflow PHPUnit

### PR DESCRIPTION
**Pull request by kenjis**
Probably now Shield works with only ~~MySQL or~~ SQLite3.

- [x] MySQL #336
- [x] Postgre #339
- [x] SQLSRV
- [x] OCI8 #402

### CODE REVIEW

**Comment by kenjis** [comment]
I was wrong. Tests failed on MySQL. 

```
There was 1 error:

1) Tests\Authentication\Authenticators\SessionAuthenticatorTest::testForgetAnotherUser
mysqli_sql_exception: Incorrect datetime value: 'nesciunt' for column 'expires' at row 1

/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:292
/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/Database/BaseConnection.php:695
/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/Database/BaseConnection.php:609
/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/Database/BaseBuilder.php:1904
/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/Model.php:278
/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/BaseModel.php:738
/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/Model.php:666
/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/Test/Fabricator.php:469
/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/Helpers/test_helper.php:38
/home/runner/work/shield/shield/tests/Authentication/Authenticators/SessionAuthenticatorTest.php:237
phpvfscomposer:///home/runner/work/shield/shield/vendor/phpunit/phpunit/phpunit:97

--

There were 2 failures:

1) Tests\Controllers\LoginTest::testLoginActionUsernameSuccess
The value of 'user' does not match expected value.
Failed asserting that two arrays are identical.
--- Expected
+++ Actual
@@ @@
 Array &0 (
-    'id' => 1
+    'id' => '1'
 )

/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/Test/TestResponse.php:264
/home/runner/work/shield/shield/tests/Controllers/LoginTest.php:139
phpvfscomposer:///home/runner/work/shield/shield/vendor/phpunit/phpunit/phpunit:97

2) Tests\Controllers\LoginTest::testLoginActionEmailSuccess
The value of 'user' does not match expected value.
Failed asserting that two arrays are identical.
--- Expected
+++ Actual
@@ @@
 Array &0 (
-    'id' => 1
+    'id' => '1'
 )

/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/Test/TestResponse.php:264
/home/runner/work/shield/shield/tests/Controllers/LoginTest.php:79
phpvfscomposer:///home/runner/work/shield/shield/vendor/phpunit/phpunit/phpunit:97
```
https://github.com/codeigniter4/shield/runs/7625886471?check_suite_focus=true

**Review by MGatner — APPROVED** [review]
The actual PR code looks good though and seems to have worked well!

**Comment by kenjis** [comment]
```
Run vendor/bin/phpunit --verbose --coverage-text --testsuite main
PHPUnit 9.5.21 #StandWithUkraine

Runtime:       PHP 7.4.30 with Xdebug 3.1.2
Configuration: /home/runner/work/shield/shield/phpunit.xml.dist
Random Seed:   1659774642

...............................................................  63 / 183 ( 34%)
............................................................... 126 / 183 ( 68%)
.........................................................       183 / 183 (100%)

Nexus\PHPUnit\Extension\Tachycardia identified these 3 slow tests:
+--------------------------------------------------------------------------+---------------+-------------+
| Test Case                                                                | Time Consumed | Time Limit  |
+--------------------------------------------------------------------------+---------------+-------------+
| Tests\\Controllers\\RegisterTest::testRegisterRedirectsToActionIfDefined | 00:00:01.01   | 00:00:00.50 |
| Tests\\Controllers\\RegisterTest::testRegisterActionSuccess              | 00:00:01.01   | 00:00:00.50 |
| Tests\\Unit\\DictionaryValidatorTest::testCheckTrueOnNotFound            | 00:00:00.74   | 00:00:00.50 |
+--------------------------------------------------------------------------+---------------+-------------+

Warning: Took 1.01s from 0.50s limit to run Tests\\Controllers\\RegisterTest::testRegisterRedirectsToActionIfDefined
Warning: Took 1.01s from 0.50s limit to run Tests\\Controllers\\RegisterTest::testRegisterActionSuccess
Warning: Took 0.74s from 0.50s limit to run Tests\\Unit\\DictionaryValidatorTest::testCheckTrueOnNotFound


Time: 00:23.047, Memory: 78.00 MB

OK (183 tests, 471 assertions)
```

**Comment by kenjis** [comment]
PHP 8.0 - OCI8 
```
There were 26 errors:

1) Tests\Authentication\Authenticators\AccessTokenAuthenticatorTest::testLoginByIdNoToken
ErrorException: oci_execute(): ORA-01400: cannot insert NULL into ("ORACLE"."db_auth_token_logins"."identifier")

/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/Database/OCI8/Connection.php:198
/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/Database/BaseConnection.php:693
/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/Database/BaseConnection.php:620
/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/Database/BaseBuilder.php:1916
/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/CodeIgniter.php:340
/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/Test/FeatureTestTrait.php:189
/home/runner/work/shield/shield/tests/Authentication/Filters/ChainFilterTest.php:23

--

There was 1 failure:

1) Tests\Authentication\Authenticators\SessionAuthenticatorTest::testAttemptUserHavingSessionDataAttemptsAgain
Failed asserting that exception of type "ErrorException" matches expected exception "CodeIgniter\Shield\Exceptions\LogicException". Message was: "oci_execute(): ORA-00904: "DB_AUTH_IDENTITIES"."SECRET": invalid identifier" at
/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/Database/OCI8/Connection.php:198
/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/Database/BaseConnection.php:693
/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/Database/BaseConnection.php:620
/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/Database/BaseBuilder.php:1585
/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/Model.php:249
/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/BaseModel.php:622
/home/runner/work/shield/shield/src/Models/UserModel.php:183
/home/runner/work/shield/shield/src/Authentication/Authenticators/Session.php:287
/home/runner/work/shield/shield/src/Authentication/Authenticators/Session.php:103
/home/runner/work/shield/shield/tests/Authentication/Authenticators/SessionAuthenticatorTest.php:369
.

ERRORS!
Tests: 183, Assertions: 372, Errors: 26, Failures: 1.
```

**Comment by datamweb** [comment]
All green,
Do we need to list the databases that Shield supports in the documentation?

**Comment by kenjis** [comment]
> Do we need to list the databases that Shield supports in the documentation?

It is better to have it.
If you send a PR, please mention `MySQL (InnoDB)`.

**Pull request merged**
