### PR TITLE
fix: translate fa-IR 

### PR DESCRIPTION
**Pull request by datamweb**
Hello **engineers!**
The language file was modified for Persian.
(related to PR #160)

### CODE REVIEW

**Comment by datamweb** [comment]
@kenjis , Considering that Persian is RTL.
Takes **PHPCSFixer** errors.
Is there a suggestion to fix this problem by keeping the comments?
Or should I delete English comments altogether?

**Comment by kenjis** [comment]
@datamweb RTL and the English comments have nothing to do with.

>    1) codeigniter-shield/src/Language/fa/Auth.php (single_blank_line_at_eof)

You just forgot a line break at the end of the file.

Run cs-fix and you will get the fixed file.
```
$ composer cs-fix
```

**Review by kenjis — APPROVED** [review]

**Comment by datamweb** [comment]
@kenjis Problem cs was resolved, but the translation was broken, so I deleted the English comets.

**Review by kenjis — DISMISSED** [review]

**Review by kenjis — APPROVED** [review]
I've confirmed all items are translated.

**Pull request merged**
